### ISSUE TITLE
Use a better type for storing the due date of a task

### ISSUE THREAD

**Issue by thompsy** [Ewan10/Task-Manager#11]
Currently, for simplicity, we're just storing the date and time that a task is due using a `String`. It would be helpful to store this data using a more appropriate data type so that we could filter the tasks and show, for example, those tasks due today, or those tasks that were due last week.

I recommend that you use [joda-time](https://www.joda.org/joda-time/quickstart.html) library for this rather than Java's built-in date handling. You'll need to figure out how to parse the `String`s supplied by the user into a better data type (hint: you will not need to do the actual parsing yourself, the functionality of the library should be enough.)

**Comment by Ewan10** [comment]
I am studying the joda-time library and I need some specifications. There are the LocalDate, the LocalTime and the DateTime classes among others in the library. Currently we store the date and the time into separate strings. So for the date I can use the LocalDate class without a time.

 And the LocalTime class for processing the time string. For the date I assumed that the user enters the date in the format "dd/MM/yyyy" so as to construct the appropriate parser. 

As for the time in what form should we assume the user enters it so as to construct the parser? If I assume the user enters the time as "hh:mm" then I can convert it to LocalTime in one line: `LocalTime time = LocalTime.parse("12:05");` 

The assumption of the form of the strings the user enters the date and time will affect how I will construct the parsers. I think for the current phase we should make the above simple assumptions for the time and not complicate it further.
 Shall I go for the separate LocalDate and LocalTime classes?

**Comment by Ewan10** [comment]
I know how to create a LocalDate from a date as string and I know how to create a LocalTime object from time as string. However you said that I must decouple the operations in the list of tasks from input reception and parsing. So I can create a method that will take as input the date and the time or even the title as strings, it will do the parsing with the joda library objects and then how or where the task object will be created and stored in the list of tasks, the taskStorage? 

Will that parsing method create a task with those fields title, LocalDate, LocalTime and return the task as a reference inside the taskManager which will call the add method passing this task instance as a parameter? Then that add method will consist of a single line: `taskStorage.add(thisTask)` (which seems weird but it obeys the software design principles). We know the principle of design classes for readability, **testability** and extensibility-scalability. But how are those implemented in practice? We need to determine the implementation on this topic.

**Comment by thompsy** [comment]
That all sounds pretty sensible to me. In an ideal world I would probably recommend using a `DateTime` object since that will also store the timezone (and this is almost always a good idea!). However, I think your plan to use `LocalDate` and `LocalTime` is perfectly reasonable for now and avoids unnecessary complexity.

In terms of the format that you expect the date and time to be entered using, that's up to you. It doesn't really matter what format you choose as long as it's sensible like the options you suggest above. 

In terms of where the parsing should happen, there are a few different options:

1. You could add a method to `Main.java` which takes a `String` and produces a `LocalDate` (and likewise for the time), or throws an exception if it can't be parsed. You could then call this method to parse the date before you call `taskManager.add()`. This is a reasonable approach but it does mean that `Main.java` starts to have more responsibilities than it should. Currently it's only responsibility is parsing the command line arguments and calling the appropriate methods.
2. You could have the `Task` constructor take a `String` type for the date and time and have the constructor do the parsing or throw an exception if it can't. This is nicer because it makes sense that the `Task` class should know how to parse the `String`s it needs for it's fields.
3. You could handle the parsing in the `TaskManager` class by having the `TaskManager.add()` method take `String`s for the date and time and do the conversion there before passing the proper types to the `Task` constructor. This isn't a bad approach either as it's reasonable for the `TaskManager` to know how to parse the data used to construct tasks. 

There are other approaches you could take and this is a good example of a decision that isn't immediately obvious. There's no 'correct' answer here just ones that fit better depending on what approach you want to take. Those are my three suggestions but I'll leave the choice up to you!

**Comment by Ewan10** [comment]
Firstly I went for the choice of the TaskManager class to do the parsing of the date and time (I was thinking maybe to create a assistant class for supporting operations to the TaskManager. Perhaps later if more assistive operations accumulate.) After the changes introduced with LocalDate and LocalTime I can add a Task and i can view it with the -v option. 

If I leave the program to store the session by default in fileStorage.json and I try to load the session then a function-constructor Chronology() from the joda library throws an exception as it is initialized with no argumets as the message says. I am thinking the possibility to have to convert the LocalDate and LocalTime of the tasks to strings before saving them in a file and during loading to reconvert them to LocalDate and LocalTime for the new session in order to circumvent this problem. Or investigate further the joda library or something else. Do you want me to push the modified files to have a look?

**Comment by thompsy** [comment]
Putting the parsing code in the `TaskManager` sounds good.

Yes, you will need to update the saving and loading code to store and load the dates and times as strings in the Json structure. You should be able to set the date format used by the Gson library.

Feel free to push the modified files. I'm happy to take a look.
