### ISSUE TITLE
Allow the user to specify the filename to use as the data store

### ISSUE THREAD

**Issue by thompsy** [Ewan10/Task-Manager#12]
Currently we're storing the tasks in a Json file with the hard-coded filename `fileStorage.json`. It would be nice to allow the user to choose this filename when they run the program (this will also make integration testing easier in due course).

The program would then be invoked like this:
`tasks.sh --view -f my-file.json`

Note that if the user does not supply a filename, the default file should continue to be used.

**Comment by Ewan10** [comment]
I incorporarated this enhancement of functionality about a week ago.
