### ISSUE TITLE
Refactoring the load method

### ISSUE THREAD

**Issue by Ewan10** [Ewan10/Task-Manager#13]
I see a design decision here and I seek instructions before moving into the implementation. It should be expected that the Gson lib. methods save the objects as strings and load them from strings back to the List<Task>. This is why a Task with fields `task(String title, LocalDate d, LocalTime t)` cannot be initialized after the load is invoked. 

A way I thought to bypass this problem was to overload the Task constructor with all fields as strings, then I will call a method `stringToJoda()` that will convert a Task object with string fields to a Task with LocalDate and Time fields. This method could be invoked after the command line when the user enters the strings and could create a Task with string fields. Next invoking this method will make a Task with the fields from Joda types, LocalDate,...  What makes me unsure about this approach is that I will have inside the Task double field of two different types and two versions of constructors as `String date, String time` but also `LocalDate date and LocalTime time`. 

I am not sure it that design pattern is appropriate. (I didn't push any files yet as I didn't consider necessary in this phase.)

**Comment by thompsy** [comment]
Good question Ioannis. Your intuition about storing two fields with the same data is correct. This is almost always a bad idea!

What you need to do here is tell the Gson library how to serialize and deserialize the `LocalDate` and `LocalTime` classes that you're using. Gson knows how to handle all the default data types but it can't really know how to serialize and deserialize all the possible data types you might throw at it.

Something like this should do the job: https://gist.github.com/hivemind02/7885704
I would pop it in a separate file and use it in the load and save methods.

Also, try and keep comments related to an issue in the same thread. So this comment is really related to #11 so it should really be posted there. That allows all the related things to stay together and makes it easier for others to follow the conversation if need be.

**Comment by Ewan10** [comment]
I pushed a file LocalDateTypeAdapter.java that implements the serialization for a LocalDate object. I feel again that I reach a design decision point so I pose the issue. The serialization in this mentioned file serializes a LocalDate object and a Gson object is created to be parsed and written later in a file from the save method.

If you look up the save method inside the TaskManager.java as it is implemented now it creates a json object on the first lines by taking the List<Task> taskstorage as argument. Which contains Task objects and each Task has fields a String, a LocalDate and a LocalTime field. The methods in LocalDateTypeAdapter.java serialize a LocalDate or can be modified to serialize a LocalTime object. Those types are fields in a Task. 

The question is should I rewrite the save (and load method later) to decompose each Task object from the list to String title, LocalDate date and LocalTime and parse-serialize them separately and deserialize them and composing them to recreate the Task objects that will reinitilize the List<Task>? If I do that immediately the save and load methods will contain many more operations and length and I am wondering whether there is any design pattern for such processes. Obviously those issues occur in software dev. and there might be some ready methodology otherwise the serialization becomes very low level process and from the problem space we are occupied on the machine space. 

In the previous version of the save and load methods where I used FileInputStream and FileOutputStream I would pass as argument the taskManager object. On the online compiler it parsed the taskManager object and I was able to reload it. On VSCode it had some bugs and as you proposed to convert the objects to human readable format like json I deleted that implementation and I introduced the Gson library. I was surprised of the high level of serialization. It parsed a taskManager object with a List<Task> field which contained Task objects which in turn contained fields of string and Date and Time from the java.Date library.

**Comment by thompsy** [comment]
Good question Ioannis. The fact is that the adapter that you've created should allow the Gson library to correctly serialize and deserialize the `LocalDate` and (once you've implemented that part) `LocalTime` objects without any additional code.

The one thing that you'll want to make sure is that in the `save()` and `load()` methods you use a `Gson` object that has been constructed to use the new type adapter you've created. So, rather than using `new Gson()` you should instead use something like `new GsonBuilder().registerTypeAdapter(LocalDate.class, new LocalDateTypeAdapter()).create();`. This will create a new `Gson` object which knows how to serialize and deserialize `LocalDate` types. You can then call `fromJson()` and `toJson()` using this newly created `Gson` object.

**Comment by Ewan10** [comment]
OK I am going to clarify further how I am going to go with the implementation and what exactly was the obstacle (I pushed the TaskManager.java to be able to see the relevant lines of the save and load methods). If you look the first lines of the save method you 'll see
 `public void save(String fileName) {
        Gson jsonObject = new LocalDateTypeAdapter().getGson();
        String jsonObjectAsString = jsonObject.toJson(taskStorage);`

A json is created from LocalDateTypeAdapter and then try to parse the taskStorage which has objects containing both LocalDate and LocalTime.

and the last lines of the LocalDateTypeAdapter are: 
`private Gson gson = new GsonBuilder().registerTypeAdapter(LocalDate.class, new LocalDate()).create();

 Gson getGson() {
    return gson;
}` 
So the getGson returns a Gson object which is created by ** only one type**, the LocalDate.class. The issue is that with that code of the TypeAdapter class I can create a gson using **one type either LocalDate or LocalTime**. But I want to serialize Task objects that have **both of those types** plus a string. The solution to that I am thinking to implement is to create objects with a DateTime field that will replace the two LocalDate and LocalTime fields. The DateTime field will be initialized by the date and time strings the user enters on the command line "dd/mm/yyyy" "hh:mm".

**Comment by thompsy** [comment]
So, having the `Gson` object as part of the adapter type is not a good idea, precisely for the reason you're seeing. I would remove both the `Gson` field and the `getGson()` method from the adapter class.

Then in the `load()` method of the `TaskManager` you can create a new `Gson` like this:
```
Gson gson = new GsonBuilder()
                    .registerTypeAdapter(LocalDate.class, new LocalDateTypeAdapter())
                    .registerTypeAdapter(LocalTime.class, new LocalTimeTypeAdapter())
                    .create();
```

This way you can registry as many type adapters as you want. It's worth knowing about this object construction pattern by the way. It's called the builder pattern. There's a good overview of this in the second item of the Effective Java book which I think you have.

**Comment by Ewan10** [comment]
I pushed all the java files and the pom. I cannot detect the cause of the malfunction. I may not implement the GsonBuilder correctly. One note is the file you sent me to look up for the TypeAdapter class in that original file the class is marked static.

In my implementation for LocalDateTypeAdapter.java and LocalTimeTypeAdapter.java I marked the classes public and removed the static cause with the static VSCode showed the message "error invalid access modifier. Can be abstract public..."  

How the program behaves currently. It adds a task and can view and by default is saved in fileStorage.json. Next if I just run -v for viewing the task it disappears from fileStorage.json it is erased  and it is not printed on the screen without calling load. Just putting the option -v and calling viewAll().  Maybe in the GsonBuilder I had explicitly to declare twice the String class for the title and the status? I am not sure.  Because the issue stems from the implementation of the builder pattern I pushed the files as I cannot detect the cause of the error with certainty. I played with the cli adding tasks, isolating the load and save methods but it seems that the implementation is wrong.

**Comment by Ewan10** [comment]
I am just revising and studying the builder pattern from Bloch's and thinking how it can correlate to the case of the jsonObject and Task.

**Comment by thompsy** [comment]
Ok, I've had a look at the loading issues that you're having. It's not entirely clear what parameters you are using when you run the program but I expect it's because you're not using `--load` every time.

With the current code on your branch, if you do not use the `--load` parameter the `TaskManager` will have an empty list of tasks. This empty list will then be saved to the standard output file overriding whatever was there before.

I suggest you remove the `--load` and `--save` parameters as a user would almost certainly want to load from the existing file and save on exit otherwise the program would not be doing anything useful!

**Comment by Ewan10** [comment]
An implementation decision arises again. It has to do with the LocalDate objects. On the cmd I expect the user to enter the date in the format "dd/mm/yyyy" and the time as "hh:mm". Then I use a formatter to create the LocalDate and LocalTime fields of a Task.

Then when I invoke the save method and write in the fileStorage.json the fields of the tasks for LocalDate and LocalTime are written in the format "yyyy-mm-ddT-00:00:000" and similarly for the Local Time "????-??-??Thh:mm:0000" roughly. When I call the load method I create from fileStorage.json one string which contains all the record in this file and I use this string named lines in the code to recreate the new List<Task> taskStorage. This triggers runtime exceptions of illegalArgumentException. This occurs because it tries to recreate the LocalDate and LocalTime objects from the format shown above in the fileStorage.json. But in the add method of TaskManager I create each task using a formatter and a helper method stringToJoda() which expects for LocalDate the format of "dd/mm/yyyy". This is the format it expects from the user on the cli as I explained at the beginning.

 Those two different formats create a conflict. And two different implementations can be applied as I can perceive. I am also suspecting that I may not call the registerTypeAdapter method at the GsonBuilder. I don't know if a teleconference would be more suitable. If you think so then arrange the time. 

I call the registerTypeAdapter() as `new GsonBuilder()
                          .registerTypeAdapter(LocalDate.class, new LocalDateTypeAdapter())
                          .registerTypeAdapter(LocalTime.class, new LocalTimeTypeAdapter())
                          .create();`

but I suspect if I should call it as 

`new GsonBuilder()
                           .registerTypeAdapter(String.class, new StringTypeAdapter())
                          .registerTypeAdapter(LocalDate.class, new LocalDateTypeAdapter())
                          .registerTypeAdapter(LocalTime.class, new LocalTimeTypeAdapter())
                          ..registerTypeAdapter(String.class, new StringTypeAdapter())
                          .create();`

To include the title and status string fields.

**Comment by thompsy** [comment]
So, there are two things here. Firstly the question of date formatting and secondly the question about whether you should be registering types to convert the title and status fields. Let's address them in that order.

In terms of the date formatting you'll want to define a single date format and a single time format that are used throughout your program. Currently, you're using three different formats:

1. In the `LocalDateTypeAdapter` you're using `ISODateTimeFormat` and specifically you're using the `dateTimeNoMillis` format. It's worth noting that this is giving you both the date and the time, whereas your probably just want the time.
2. In the `LocalTimeTypeAdapter` you are using the same format as above again with the `dateTimeNoMillis`. You probably want to be using just a time format here that doesn't involve the date at all.
3. In the `stringToJodaTask` method you're using the format `dd/MM/yyyy` for the date.

Having three different formats is causing you problems! The general recommendation is that any piece of data (like a date format) should only be defined in one place. It shouldn't be scattered about your code as then differences arise like this.

I suggest you define a date and time format in `TaskManager`. Using `DateTimeFormat.forPattern()` is probably the easiest approach. You can then use these formatter objects wherever you are parsing or serializing dates and times i.e. in the three locations above. You'll need to think about the best way to get this format data into the type adapters you've defined.

Ok, the second thing is whether you need a type adapter to handle the strings which represent the title and status of the tasks. The answer to this is "No." Strings are a type that is already understood by Json so the serialization and de-serialization is automatic. The reason that you need to specify type adapters for your date and time is that Json has no native date and time types so you are storing them as strings. The `Gson` library knows about strings, but it doesn't know anything about your date or time formats so you need to use the type adapters to tell it how to handle them. 

Hopefully, that should give you enough to keep at it. If not, let me know and we can schedule a chat!

**Comment by Ewan10** [comment]
I have a working implementation for this enhancement of functionality.
