### ISSUE TITLE
Refactoring approach to user input

### ISSUE THREAD

**Issue by thompsy** [Ewan10/Task-Manager#7]
The `TaskManager` class is doing a lot of different things. In order to start separating out its responsibilities and make testing easier we're going to refactor out the user input handling that exists there.

All of the user input should be handled in the `Main` class for now. This includes reading input data from the command line and validating it. The validated input can then be passed into the public methods of the `TaskManager` which will do the actual work.

Let's consider adding a new task as a small worked example. A new task needs the following data: 
* title
* date
* time

In order to pass these on the command line we would run the program something like this:
`taskManager add --title "my title" --date "12/12/2021" --time "10:10am"`

The `Main` class should then be able to gather this information and pass it into the public `add` method of the `TaskManager`. The `add` method will need to be updated to accept these parameters.

**Comment by Ewan10** [comment]
Andrew I realized that I do not understand how the apache cli accepts input. I added options and parse the command line and I read them again I watched some videos about the cli which didn't help once again irrelevant. I don' t know how to refactor the add method wherein I call the userinput method validateTime and ValidateDate methods. Also Whenever I run command there are errors I cannot run it with any command. I realized how I am familiar with with the interactive reading of input and printing on a console window. I need a session and it would be helpful to write some sample code to see how it is run the command line as all those retards have not  a single example of running it. 

private LocalDate validateDate() {
    String date;
    int[] userDate = { 0, 0, 0 };
    String[] dateAsString = {};

    do {
      do {
        date = userInput("Enter the date as: YYYY-MM-dd");
      } while (!Pattern.compile("\\d{4}?\\-\\d{2}?\\-\\d{2}?").matcher(date).matches());

      dateAsString = date.split("-");
      for (int i = 0; i < userDate.length; i++)
        userDate[i] = Integer.parseInt(dateAsString[i]);
    } while (!(userDate[0] >= 2021) || (!(userDate[1] >= 1 && userDate[1] <= 12)) || (!(userDate[2] >= 1
        && userDate[2] <= 31)));

    // Date validation according to numeric values of 31, 12 and a positive number for the day, the month and the year respectively.
    return LocalDate.parse(date);
  }
private String userInput(String expression) {
    // the user to enter input and it returns that input string.
    String s;
    Scanner sx = new Scanner(System.in);
    System.out.println(expression);
    s = sx.nextLine();
    sx.close();
    return s;
  }

**Comment by thompsy** [comment]
Ok Ioannis, I'll email you to setup a session where we can walk through the basics of how to use Apache CLI. 

One other important thing that I need to mention here is your approach to communication. Working on your communication skills is very important if you ever want to get a job in the field. Here are a few pointers that could help you improve:

- Be more specific. You mention that you're getting some errors. What are the errors exactly, how did you run the program, what arguments did you provide? Without these kinds of details I have no idea how to help you with these errors. Likewise, you say that you don't know how to refactor some of the methods. That's fine and to be expected but again more specificity is helpful here. Did you make any attempt to do so? What approach did you take? Why did it not work the way you expected? Basically, more information will help me to help you much more effectively.
- You used a derogatory term (retards) to refer to someone (it wasn't clear who you were actually referring to here). This kind of language is very unprofessional and does not give a good impression of you. Perhaps there's a cultural difference here but in the UK and US at least this kind of language is just not acceptable in a professional context. You may be frustrated with your progress and lack of understanding and that's fine, but to refer to other people in derogatory ways is not appropriate.

**Comment by thompsy** [comment]
Here's a small demo project that shows how to use the Commons CLI library: https://github.com/thompsy/commons-cli-example

You should be able to clone this and run the Maven command listed in the Readme to run it. If you have a look over this before our call that would be helpful.

**Comment by Ewan10** [comment]
I know derrogatory language is inappropriate in a professional context. I 'd say it is in any society unacceptable. The executive will fire you instantly. It won't happen again boss. 

Now your example helps to detect the obstacles I have with the cli. I cloned the example repo. If I type 'mvn compile' it builds successfully. First of all I opened the folder of the cloned repo in VSCode and on the terminal I move in the commons-cli-example folder. If I type on the terminal the full command: 

mvn compile exec:java -Dexec.mainClass="uk.co.downthewire.example.Main" \ -Dexec.args="-a 'Example task' --date '12/12/21' -t '10am'"
Then build errors appear. Now if I run it on Git bash the errors are such:

ERROR] Unknown lifecycle phase " -Dexec.args=-a 'Example task' --date '12/12/21' -t '10am'". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

If I do it on powershell the errors are such: 

[ERROR] Unknown lifecycle phase ".mainClass=uk.co.downthewire.example.Main". You must specify a valid lifecycle phase at <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phaitialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generates-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-pactegration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-si
site-deploy. -> [Help 1]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

I do not know the syntax of the command line as exec: java or -Dexec.args and so on and so forth. Also I noticed I don't use the getOptionValue method.

**Comment by thompsy** [comment]
Thanks Ioannis, that's helpful detail!

I had a small mistake in the command listed in the readme of the example project. I've fixed that now so the following command should work:
`mvn compile exec:java -Dexec.mainClass="uk.co.downthewire.example.Main" -Dexec.args="-a 'Example task' --date '12/12/21' -t '10am'"`

Try running that in the example project and let me know what you get.

Also, it's good practice if you put use code formatting when adding code, errors or commands into comments on Github and other places. It makes things a bit easier to read for others. You can use the "Insert Code" button on the editor. You can see some more details about Markdown, the format that's used, here: https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by thompsy** [comment]
This issue will be replaced by #8
