### ISSUE TITLE
Strip back functionality to the very basics

### ISSUE THREAD

**Issue by thompsy** [Ewan10/Task-Manager#8]
We're going to strip things back here to the minimal viable product. I've added a script that should make running the program a bit easier for now. We can use this `task.sh` script for now rather than running Maven directly.

Here's the command line interface that I'd like you to implement:
```
# Add a task
$ task.sh -a 'Example task' --date '12/12/21' --time '10am'

# List tasks. This should just print out the information for each task
$ task.sh --list"
12/12/21 10am Example task
```

Note that the program should use a default filename to store the data. This should be loaded when the program is run and saved when the program exits. For now we can forget about any data validation or sorting of tasks so be sure to delete all the code related to these things. 

This should give us a good base to add improved functionality and start some testing too.

Feel free to ask any follow-up questions.

**Comment by Ewan10** [comment]
I 've implemented an alternative version of the save method storing the tasks in json format after I  had a nightmare to setup Maven and the pom file to recognize the appropriate dependency.  I tested it and it is working. I 'll need to watch some videos how to implement the load method as well. Have a sneak peak of the save method here below: 

`public void save(TaskManager tm, String fileName) {
        Gson jsonObject = new Gson();
        String jsonObjectAsString = jsonObject.toJson(tm.taskStorage());

        try {
            FileWriter fileWriter = new FileWriter(fileName + ".json");
            fileWriter.write(jsonObjectAsString);
            fileWriter.flush();
            fileWriter.close();
        }
        catch(Exception e){
          e.printStackTrace();
          System.exit(1);
        }
  }`

**Comment by thompsy** [comment]
Good work Ioannis. Just pop a pull request up when you're done and I'll take a look!

**Comment by Ewan10** [comment]
The load method inside Main assumes there is a saved file and tries to open it. Now in case the program starts for the first time and no file has been saved I thought as a solution adding it on the next commit to create a static flag field so once the save method is invoked it sets the flag. Then a TaskManager instance checks that flag to know whether the save was called to invoke the load. Otherwise you propose a solution. That 'll be for the next commits.

**Comment by thompsy** [comment]
I'll try and have this PR reviewed for you today Ioannis. 

In terms of how to handle the missing file, a better approach would be to attempt to load the file and if you find that it doesn't exist i.e. you get `FileNotFoundException`, then you could try and create the file. It would be worth thinking carefully about where this code should live. Who, or which class, should be responsible for checking for the existence of the file?

**Comment by thompsy** [comment]
I'm closing this as your PR is good!
